"""add_origin_city_and_num_travelers

Revision ID: 2eeab09a5c50
Revises: a772ce926c2b
Create Date: 2026-08-22 14:31:09.484690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eeab09a5c50'
down_revision: Union[str, None] = 'a772ce926c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('activities', 'vibe',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('activities', 'best_for',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('budgets', 'total_budget_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('budgets_trip_id_key'), 'budgets', type_='unique')
    op.drop_index(op.f('ix_budgets_trip_id'), table_name='budgets')
    op.create_index(op.f('ix_budgets_trip_id'), 'budgets', ['trip_id'], unique=True)
    op.alter_column('cities', 'region',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('cities', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cities', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cities', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('cities', 'vibe_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('cities', 'best_months',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('cities', 'safety_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('80.0'))
    op.alter_column('cities', 'rent_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('45.0'))
    op.alter_column('cities', 'restaurant_price_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('60.0'))
    op.create_index(op.f('ix_cities_country'), 'cities', ['country'], unique=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('expenses', 'estimated_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_check_constraint('check_favorite_target', 'favorites', 'city_id IS NOT NULL OR activity_id IS NOT NULL')
    op.alter_column('itinerary_items', 'activity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('shared_links_share_token_key'), 'shared_links', type_='unique')
    op.drop_index(op.f('ix_shared_links_share_token'), table_name='shared_links')
    op.create_index(op.f('ix_shared_links_share_token'), 'shared_links', ['share_token'], unique=True)
    op.drop_constraint(op.f('uq_trip_stop_order'), 'trip_stops', type_='unique')
    op.add_column('trips', sa.Column('origin_city', sa.String(length=100), server_default='Mumbai', nullable=True))
    op.add_column('trips', sa.Column('num_travelers', sa.Float(), server_default='1', nullable=False))
    op.add_column('trips', sa.Column('transit_mode', sa.String(length=50), server_default='train', nullable=True))
    op.alter_column('trips', 'total_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('trips', 'total_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('trips', 'transit_mode')
    op.drop_column('trips', 'num_travelers')
    op.drop_column('trips', 'origin_city')
    op.create_unique_constraint(op.f('uq_trip_stop_order'), 'trip_stops', ['trip_id', 'stop_order'])
    op.drop_index(op.f('ix_shared_links_share_token'), table_name='shared_links')
    op.create_index(op.f('ix_shared_links_share_token'), 'shared_links', ['share_token'], unique=False)
    op.create_unique_constraint(op.f('shared_links_share_token_key'), 'shared_links', ['share_token'])
    op.alter_column('notifications', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('itinerary_items', 'activity_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('check_favorite_target', 'favorites', type_='check')
    op.alter_column('expenses', 'estimated_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_cities_country'), table_name='cities')
    op.alter_column('cities', 'restaurant_price_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('60.0'))
    op.alter_column('cities', 'rent_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('45.0'))
    op.alter_column('cities', 'safety_index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('80.0'))
    op.alter_column('cities', 'best_months',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('cities', 'vibe_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('cities', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('cities', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cities', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cities', 'region',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_budgets_trip_id'), table_name='budgets')
    op.create_index(op.f('ix_budgets_trip_id'), 'budgets', ['trip_id'], unique=False)
    op.create_unique_constraint(op.f('budgets_trip_id_key'), 'budgets', ['trip_id'])
    op.alter_column('budgets', 'total_budget_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.alter_column('activities', 'best_for',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('activities', 'vibe',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('activities', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
