"""add_city_and_activity_ml_columns

Revision ID: a772ce926c2b
Revises: 1a710c8212e9
Create Date: 2026-08-22 14:02:37.707940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a772ce926c2b'
down_revision: Union[str, None] = '1a710c8212e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('activities', sa.Column('vibe', sa.String(length=50), nullable=True))
    op.add_column('activities', sa.Column('best_for', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False)
    op.add_column('cities', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('cities', sa.Column('vibe_tags', sa.JSON(), nullable=False))
    op.add_column('cities', sa.Column('climate_type', sa.String(length=50), nullable=True))
    op.add_column('cities', sa.Column('best_months', sa.JSON(), nullable=False))
    op.add_column('cities', sa.Column('safety_index', sa.Float(), nullable=False))
    op.add_column('cities', sa.Column('budget_tier', sa.String(length=20), nullable=True))
    op.add_column('cities', sa.Column('rent_index', sa.Float(), nullable=False))
    op.add_column('cities', sa.Column('restaurant_price_index', sa.Float(), nullable=False))
    op.create_index(op.f('ix_cities_region'), 'cities', ['region'], unique=False)
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_favorites_activity_id'), 'favorites', ['activity_id'], unique=False)
    op.create_index(op.f('ix_favorites_city_id'), 'favorites', ['city_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_activity_id'), 'itinerary_items', ['activity_id'], unique=False)
    op.create_index(op.f('ix_shared_links_trip_id'), 'shared_links', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_trip_id'), 'trip_collaborators', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_collaborators_user_id'), 'trip_collaborators', ['user_id'], unique=False)
    op.create_index(op.f('ix_trip_stops_city_id'), 'trip_stops', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_stops_city_id'), table_name='trip_stops')
    op.drop_index(op.f('ix_trip_collaborators_user_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_trip_collaborators_trip_id'), table_name='trip_collaborators')
    op.drop_index(op.f('ix_shared_links_trip_id'), table_name='shared_links')
    op.drop_index(op.f('ix_itinerary_items_activity_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_favorites_city_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_activity_id'), table_name='favorites')
    op.drop_column('expenses', 'created_at')
    op.drop_index(op.f('ix_cities_region'), table_name='cities')
    op.drop_column('cities', 'restaurant_price_index')
    op.drop_column('cities', 'rent_index')
    op.drop_column('cities', 'budget_tier')
    op.drop_column('cities', 'safety_index')
    op.drop_column('cities', 'best_months')
    op.drop_column('cities', 'climate_type')
    op.drop_column('cities', 'vibe_tags')
    op.drop_column('cities', 'tags')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_column('activities', 'best_for')
    op.drop_column('activities', 'vibe')
    op.drop_column('activities', 'tags')
    # ### end Alembic commands ###
