"""Add domain models for Single Source of Truth

Revision ID: b055be664320
Revises: 2eeab09a5c50
Create Date: 2026-08-22 14:54:29.121505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b055be664320'
down_revision: Union[str, None] = '2eeab09a5c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('estimated_nightly_rate', sa.Float(), nullable=True),
    sa.Column('is_estimate', sa.Boolean(), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stays_city_id'), 'stays', ['city_id'], unique=False)
    op.create_index(op.f('ix_stays_id'), 'stays', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_transit_mode', sa.String(length=50), nullable=True),
    sa.Column('travel_style', sa.String(length=50), nullable=True),
    sa.Column('activity_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('ml_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_trip_id'), 'ml_predictions', ['trip_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('rec_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('current_cost', sa.Float(), nullable=True),
    sa.Column('alternative_cost', sa.Float(), nullable=True),
    sa.Column('estimated_saving', sa.Float(), nullable=True),
    sa.Column('affected_entity', sa.String(length=50), nullable=True),
    sa.Column('affected_entity_id', sa.String(length=36), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_trip_id'), 'recommendations', ['trip_id'], unique=False)
    op.create_table('transit_legs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('from_stop_id', sa.String(length=36), nullable=True),
    sa.Column('to_stop_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['transit_options.id'], name='fk_transit_leg_selected_option', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['to_stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_legs_id'), 'transit_legs', ['id'], unique=False)
    op.create_index(op.f('ix_transit_legs_trip_id'), 'transit_legs', ['trip_id'], unique=False)
    op.create_table('trip_stays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_stop_id', sa.String(length=36), nullable=False),
    sa.Column('stay_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_stays_id'), 'trip_stays', ['id'], unique=False)
    op.create_index(op.f('ix_trip_stays_trip_stop_id'), 'trip_stays', ['trip_stop_id'], unique=True)
    op.create_table('transit_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transit_leg_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('total_estimated_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_person', sa.Float(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['transit_leg_id'], ['transit_legs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transit_options_id'), 'transit_options', ['id'], unique=False)
    op.create_index(op.f('ix_transit_options_transit_leg_id'), 'transit_options', ['transit_leg_id'], unique=False)
    op.add_column('trips', sa.Column('budget_target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'budget_target')
    op.drop_index(op.f('ix_transit_options_transit_leg_id'), table_name='transit_options')
    op.drop_index(op.f('ix_transit_options_id'), table_name='transit_options')
    op.drop_table('transit_options')
    op.drop_index(op.f('ix_trip_stays_trip_stop_id'), table_name='trip_stays')
    op.drop_index(op.f('ix_trip_stays_id'), table_name='trip_stays')
    op.drop_table('trip_stays')
    op.drop_index(op.f('ix_transit_legs_trip_id'), table_name='transit_legs')
    op.drop_index(op.f('ix_transit_legs_id'), table_name='transit_legs')
    op.drop_table('transit_legs')
    op.drop_index(op.f('ix_recommendations_trip_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ml_predictions_trip_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_stays_id'), table_name='stays')
    op.drop_index(op.f('ix_stays_city_id'), table_name='stays')
    op.drop_table('stays')
    # ### end Alembic commands ###
